version: '3.1'

services:
  stringdb:
    image: postgres:11
    restart: always
    shm_size: 1G
    stop_grace_period: 5m
    environment:
      POSTGRES_USER: stringdb
      POSTGRES_PASSWORD: stringdb
      PGDATA: /var/lib/postgres/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgres/data/pgdata
      - ./shared:/opt/shared
      - ./logs:/opt/logs
    networks:
      - stringdb-net

networks:
  stringdb-net:
    external: true
